# Generated by Django 4.2 on 2023-04-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamreg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='max',
            field=models.IntegerField(default=1),
        ),
    ]
