# Generated by Django 4.2 on 2023-04-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamreg', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
